// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "generals-space/kube-operator/pkg/apis/kubegroup/v1"
	"generals-space/kube-operator/pkg/client/clientset_generated/clientset/scheme"

	rest "k8s.io/client-go/rest"
)

type KubegroupV1Interface interface {
	RESTClient() rest.Interface
	PodClustersGetter
}

// KubegroupV1Client is used to interact with features provided by the kubegroup.generals.space group.
type KubegroupV1Client struct {
	restClient rest.Interface
}

func (c *KubegroupV1Client) PodClusters(namespace string) PodClusterInterface {
	return newPodClusters(c, namespace)
}

// NewForConfig creates a new KubegroupV1Client for the given config.
func NewForConfig(c *rest.Config) (*KubegroupV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &KubegroupV1Client{client}, nil
}

// NewForConfigOrDie creates a new KubegroupV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *KubegroupV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new KubegroupV1Client for the given RESTClient.
func New(c rest.Interface) *KubegroupV1Client {
	return &KubegroupV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *KubegroupV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
