// Code generated by apiregister-gen. DO NOT EDIT.

package apis

import (
	"generals-space/kube-operator/pkg/apis/kubegroup"
	_ "generals-space/kube-operator/pkg/apis/kubegroup/install" // Install the kubegroup group
	kubegroupv1 "generals-space/kube-operator/pkg/apis/kubegroup/v1"

	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		kubegroupv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetKubegroupAPIBuilder(),
	}
}

var kubegroupApiGroup = builders.NewApiGroupBuilder(
	"kubegroup.generals.space",
	"generals-space/kube-operator/pkg/apis/kubegroup").
	WithUnVersionedApi(kubegroup.ApiVersion).
	WithVersionedApis(
		kubegroupv1.ApiVersion,
	).
	WithRootScopedKinds()

func GetKubegroupAPIBuilder() *builders.APIGroupBuilder {
	return kubegroupApiGroup
}
