// Code generated by apiregister-gen. DO NOT EDIT.

package install

import (
	"generals-space/kube-operator/pkg/apis/kubegroup"
	v1 "generals-space/kube-operator/pkg/apis/kubegroup/v1"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

func init() {
	Install(builders.Scheme)
}

func Install(scheme *runtime.Scheme) {
	utilruntime.Must(v1.AddToScheme(scheme))
	utilruntime.Must(kubegroup.AddToScheme(scheme))
	utilruntime.Must(addKnownTypes(scheme))
}

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(kubegroup.SchemeGroupVersion,
		&kubegroup.PodCluster{},
		&kubegroup.PodClusterList{},
	)
	return nil
}
