// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	kubegroupv1 "generals-space/kube-operator/pkg/apis/kubegroup/v1"
	clientset "generals-space/kube-operator/pkg/client/clientset_generated/clientset"
	internalinterfaces "generals-space/kube-operator/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "generals-space/kube-operator/pkg/client/listers_generated/kubegroup/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodClusterInformer provides access to a shared informer and lister for
// PodClusters.
type PodClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PodClusterLister
}

type podClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodClusterInformer constructs a new informer for PodCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodClusterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodClusterInformer constructs a new informer for PodCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodClusterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubegroupV1().PodClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubegroupV1().PodClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&kubegroupv1.PodCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *podClusterInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubegroupv1.PodCluster{}, f.defaultInformer)
}

func (f *podClusterInformer) Lister() v1.PodClusterLister {
	return v1.NewPodClusterLister(f.Informer().GetIndexer())
}
