// Code generated by lister-gen. DO NOT EDIT.

package v1

// PodClusterListerExpansion allows custom methods to be added to
// PodClusterLister.
type PodClusterListerExpansion interface{}

// PodClusterNamespaceListerExpansion allows custom methods to be added to
// PodClusterNamespaceLister.
type PodClusterNamespaceListerExpansion interface{}
