// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	kubegroup "generals-space/kube-operator/pkg/apis/kubegroup"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PodCluster)(nil), (*kubegroup.PodCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PodCluster_To_kubegroup_PodCluster(a.(*PodCluster), b.(*kubegroup.PodCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubegroup.PodCluster)(nil), (*PodCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubegroup_PodCluster_To_v1_PodCluster(a.(*kubegroup.PodCluster), b.(*PodCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodClusterList)(nil), (*kubegroup.PodClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PodClusterList_To_kubegroup_PodClusterList(a.(*PodClusterList), b.(*kubegroup.PodClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubegroup.PodClusterList)(nil), (*PodClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubegroup_PodClusterList_To_v1_PodClusterList(a.(*kubegroup.PodClusterList), b.(*PodClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodClusterSpec)(nil), (*kubegroup.PodClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec(a.(*PodClusterSpec), b.(*kubegroup.PodClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubegroup.PodClusterSpec)(nil), (*PodClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec(a.(*kubegroup.PodClusterSpec), b.(*PodClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodClusterStatus)(nil), (*kubegroup.PodClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus(a.(*PodClusterStatus), b.(*kubegroup.PodClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubegroup.PodClusterStatus)(nil), (*PodClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus(a.(*kubegroup.PodClusterStatus), b.(*PodClusterStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_PodCluster_To_kubegroup_PodCluster(in *PodCluster, out *kubegroup.PodCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_PodCluster_To_kubegroup_PodCluster is an autogenerated conversion function.
func Convert_v1_PodCluster_To_kubegroup_PodCluster(in *PodCluster, out *kubegroup.PodCluster, s conversion.Scope) error {
	return autoConvert_v1_PodCluster_To_kubegroup_PodCluster(in, out, s)
}

func autoConvert_kubegroup_PodCluster_To_v1_PodCluster(in *kubegroup.PodCluster, out *PodCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubegroup_PodCluster_To_v1_PodCluster is an autogenerated conversion function.
func Convert_kubegroup_PodCluster_To_v1_PodCluster(in *kubegroup.PodCluster, out *PodCluster, s conversion.Scope) error {
	return autoConvert_kubegroup_PodCluster_To_v1_PodCluster(in, out, s)
}

func autoConvert_v1_PodClusterList_To_kubegroup_PodClusterList(in *PodClusterList, out *kubegroup.PodClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kubegroup.PodCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_PodClusterList_To_kubegroup_PodClusterList is an autogenerated conversion function.
func Convert_v1_PodClusterList_To_kubegroup_PodClusterList(in *PodClusterList, out *kubegroup.PodClusterList, s conversion.Scope) error {
	return autoConvert_v1_PodClusterList_To_kubegroup_PodClusterList(in, out, s)
}

func autoConvert_kubegroup_PodClusterList_To_v1_PodClusterList(in *kubegroup.PodClusterList, out *PodClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PodCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kubegroup_PodClusterList_To_v1_PodClusterList is an autogenerated conversion function.
func Convert_kubegroup_PodClusterList_To_v1_PodClusterList(in *kubegroup.PodClusterList, out *PodClusterList, s conversion.Scope) error {
	return autoConvert_kubegroup_PodClusterList_To_v1_PodClusterList(in, out, s)
}

func autoConvert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec(in *PodClusterSpec, out *kubegroup.PodClusterSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec is an autogenerated conversion function.
func Convert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec(in *PodClusterSpec, out *kubegroup.PodClusterSpec, s conversion.Scope) error {
	return autoConvert_v1_PodClusterSpec_To_kubegroup_PodClusterSpec(in, out, s)
}

func autoConvert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec(in *kubegroup.PodClusterSpec, out *PodClusterSpec, s conversion.Scope) error {
	return nil
}

// Convert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec is an autogenerated conversion function.
func Convert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec(in *kubegroup.PodClusterSpec, out *PodClusterSpec, s conversion.Scope) error {
	return autoConvert_kubegroup_PodClusterSpec_To_v1_PodClusterSpec(in, out, s)
}

func autoConvert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus(in *PodClusterStatus, out *kubegroup.PodClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus is an autogenerated conversion function.
func Convert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus(in *PodClusterStatus, out *kubegroup.PodClusterStatus, s conversion.Scope) error {
	return autoConvert_v1_PodClusterStatus_To_kubegroup_PodClusterStatus(in, out, s)
}

func autoConvert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus(in *kubegroup.PodClusterStatus, out *PodClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus is an autogenerated conversion function.
func Convert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus(in *kubegroup.PodClusterStatus, out *PodClusterStatus, s conversion.Scope) error {
	return autoConvert_kubegroup_PodClusterStatus_To_v1_PodClusterStatus(in, out, s)
}
